---

- name: create deployment user
  action: user name={{ deployment_user }} shell=/bin/bash groups=admin append=yes

- name: install cryptostick public key
  action: authorized_key user={{ deployment_user }} key="{{ lookup('file', '/home/ding/.ssh/amie_ubuntu_id_rsa.pub') }}"

- name: install build depends for Rbenv, curl, postgres lib
  apt: pkg={{ item }} state=latest install_recommends=no update_cache=yes
  with_items:
          - build-essential
          - git
          - libcurl4-openssl-dev
          - libmysqlclient-dev
          - libreadline-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
          - zlib1g-dev
          - curl
          - libpq-dev
          - openjdk-7-jdk
          - vim

